# Setup
title:               Nicola Ariutti
tagline:             'my personal website'
description:         'sound and code'
url:                 ''
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Nicola Ariutti
  url:               https://twitter.com/ariutti
  email:

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
